# Generated by Django 4.2.2 on 2023-06-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NacebelCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("code", models.CharField(max_length=5)),
                ("parent_code", models.CharField(max_length=5)),
                ("label_fr", models.CharField(max_length=255)),
                ("label_nl", models.CharField(max_length=255)),
                ("label_en", models.CharField(max_length=255)),
                ("label_de", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="NacebelCodeAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deductibleFormula",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=255,
                    ),
                ),
                (
                    "coverageCeilingFormula",
                    models.CharField(
                        choices=[("S", "Small"), ("L", "Large")], max_length=255
                    ),
                ),
                (
                    "nacebel_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quotes.nacebelcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NacebelCodeCoverAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.CharField(max_length=255)),
                (
                    "nacebel_code_advice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.nacebelcodeadvice",
                    ),
                ),
            ],
        ),
    ]
