# Generated by Django 4.2.2 on 2023-06-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("enterprise_number", models.CharField(max_length=255)),
                ("natural_person", models.BooleanField()),
                ("annual_revenue", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="LeadContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="SimulatedQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available", models.BooleanField()),
                ("coverage_ceiling", models.FloatField()),
                ("deductible", models.FloatField()),
                ("remote_quote_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="nacebelcodecoveradvice",
            name="nacebel_code_advice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover_advices",
                to="quotes.nacebelcodeadvice",
            ),
        ),
        migrations.CreateModel(
            name="QuoteSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deductible_formula",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=2,
                    ),
                ),
                (
                    "coverage_ceiling_formula",
                    models.CharField(
                        choices=[("S", "Small"), ("L", "Large")], max_length=2
                    ),
                ),
                ("codes", models.ManyToManyField(to="quotes.nacebelcode")),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.enterprise",
                    ),
                ),
                (
                    "lead_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.leadcontact",
                    ),
                ),
                (
                    "simulated_quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.simulatedquote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoverPremium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.CharField(max_length=255)),
                ("premium", models.FloatField()),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covers",
                        to="quotes.simulatedquote",
                    ),
                ),
            ],
        ),
    ]
