# Generated by Django 4.2.2 on 2023-06-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_enterprise_leadcontact_simulatedquote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvicedCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.CharField(max_length=255)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adviced_covers",
                        to="quotes.quotesimulation",
                    ),
                ),
            ],
        ),
    ]
