# Generated by Django 4.2.2 on 2023-06-18 11:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_advicedcover"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotesimulation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
