# Generated by Django 4.2.2 on 2023-06-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_alter_enterprise_enterprise_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotesimulation",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="quotes.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="quotesimulation",
            name="lead_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="quotes.leadcontact",
            ),
        ),
    ]
