# Generated by Django 4.2.2 on 2023-06-19 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0006_alter_quotesimulation_enterprise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advicedcover",
            name="cover",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="coverpremium",
            name="cover",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="coverpremium",
            name="premium",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="annual_revenue",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="enterprise_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="legal_name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="leadcontact",
            name="address",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="leadcontact",
            name="firstname",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="leadcontact",
            name="lastname",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="leadcontact",
            name="phone",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="nacebelcodeadvice",
            name="coverageCeilingFormula",
            field=models.CharField(
                choices=[("S", "Small"), ("L", "Large")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="nacebelcodeadvice",
            name="deductibleFormula",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="nacebelcodecoveradvice",
            name="cover",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="quotesimulation",
            name="coverage_ceiling_formula",
            field=models.CharField(
                choices=[("S", "Small"), ("L", "Large")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="quotesimulation",
            name="deductible_formula",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="simulatedquote",
            name="coverage_ceiling",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="simulatedquote",
            name="deductible",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
